language: python
fast_finish: true

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  
os:
  - linux

notifications:
  email: false

git:
  depth: 3

before_install:
  - pip -q install coveralls

install: pip install -e .

script: coverage run Test/test_isr.py -v

after_success: coveralls
