[build-system]
requires = [
    "setuptools>=42",
    "versioneer-518",
    "wheel",
    "numpy",
    "scipy"
    "sphinx_rtd_theme"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "Test"
]