
package:
  name: isrspectrum
  version: 2.0.2

source:
  git_url: https://github.com/jswoboda/ISRSpectrum.git
  git_rev: 2.0.2

build:
  noarch: True
  
requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - six
    - nose
    - pandas
    - seaborn

  run:
    - python
    - pandas
    - scipy
    - seaborn
    - jupyter

test:
  imports:
    - ISRSpectrum

about:
  home: https://github.com/jswoboda/ISRSpectrum
  license: MIT License
  summary: Creates IS spectra
