package:
  name: isrspectrum
  version: 4.0.9

source:
  git_url: https://github.com/jswoboda/ISRSpectrum.git
  git_rev: 4.0.9

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.20
    - scipy
    - six
    - nose
    - pandas
    - seaborn

  run:
    - python
    - pandas
    - scipy
    - seaborn
    - jupyter

test:
  imports:
    - ISRSpectrum

about:
  home: https://github.com/jswoboda/ISRSpectrum
  license: MIT License
  summary: Creates IS spectra
  description: |
    This is a Python module to calculate an incoherent scatter spectrum based off of Kudeki and Milla's 2011 IEEE Geophysics paper.
  dev_url: https://github.com/jswoboda/ISRSpectrum
