name: publish_conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: publish-to-conda
      uses: TomographicImaging/conda-package-publish-action@v2
      with:
        subDir: 'recipes/conda'
        publish: true
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}



 